let quotes =  [
    "Which is better, to be born good or to overcome your evil nature through great effort?", 
    "There is no such thing as being too cautious.", 
    "You shall not attain knowledge unless you respect the teacher and the knowledge itself.", 
    "Rest is only for the dead.", 
    "Change is inevitable. Change is sacred.", 
    "Risk is always there. No exceptions.", 
    "People hate the odd and what goes beyond their perception.", 
    "Even a good intention needs thorough judgement and right timing.", 
    "It is better to have frequent small victories than few great victories.", 
    "Admittance on evil is evil in itself.", 
    "There are those who is lifeless while living, and those who lives while being lifeless.", 
    "As high you pride on, so will you fall.", 
    "Even those with great loyalty are still vulnerable to the fear of being replaced.", 
    "Danger is relative.", 
    "Following the rules does not create success. It just eliminates extremes - both good and bad.",
    "Anything better aligned to fit a unique scenario is going to be problematic on average. And qualities that are generally good can be bad at the extremes.",
    "The quality of a society can more important than your place in that society.",
    "Everything we do in life is a trade-off. Choosing to do one thing means not doing something else. The price of anything is the amount of life you exchange for it.",
    "We always think we need more. More help, more motivation, more energy. But in our current world the answer is often the exact opposite. We need less, fewer distractions, fewer goals, fewer responsibilities.",
    "Fantasizing gives us the reward before we have accomplished the task and saps the energy we need to realize it.",
    "God isn't finished with you just yet.",
    "One who thinks and reflects develops his foresight and vision.",
    "The true greatness of man lies in his capacity for eternal progress.",
    "Knowledge is not what is memorised. Knowledge is what benefits.",
    "Never have I dealt with anything more difficult than my own soul, which sometimes helps me and sometimes opposes me.",
    "Peace and Jealousy can not live in the same heart... one of them must leave.",
    "When the heart weeps for what it has lost, the spirit laughs for what it has found.",
    "You won't understand why it's so hard to change people until you realize how hard it is to change yourself.",
    "When you stop chasing the wrong things, you give the right things a chance to catch you.",
    "And in the end, it's not the years in your life that count. It's the life in your years."
]